trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'AJAY'
  resourceGroupName: 'AJAY'
  location: 'EAST US'
  templateFile: './main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Pay-As-You-Go (2f5597c4-eec3-493f-aefa-ca20c3b3e83e)'
    subscriptionId: '2f5597c4-eec3-493f-aefa-ca20c3b3e83e'
    location: 'East US'
    #templateLocation: 'Linked artifact'
    #deploymentMode: 'Validation'
    #deploymentName: 'DeployPipelineTemplate'